basePath: /
definitions:
  models.TrimmedLink:
    properties:
      id:
        type: integer
      link:
        type: string
      trimmed:
        type: string
      userId:
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      trimmedLinks:
        items:
          $ref: '#/definitions/models.TrimmedLink'
        type: array
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple link shortner api. You can visit the GitHub repository
    at https://github.com/Xavier577/link-trim
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Trim-Sever
  version: "1.0"
paths:
  /:link_uuid:
    get:
      operationId: redirect-to-original-link
      parameters:
      - description: short uuid
        in: path
        name: link_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "300":
          description: ""
        "404":
          description: ""
      summary: redirect to the original link from the uuid
  /api/v1/user/all:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: get all the users in the database
swagger: "2.0"
